
[package]
edition = "2021"
name = "takeoff_calculator"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true }
tokio = { workspace = true }
napi-derive = { workspace = true }
uom = { workspace = true }
geo = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
takeoff_core = { workspace = true }
dashmap = { version = "6.1.0", features = ["serde"] }
crossbeam = { version = "0.8.4" }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
